---
title: 'xal3: Viscosos Pero Sabrosos'
author: "PAGuardado"
date: "9/8/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library("tidyverse")
```
```{r}
xal3 <- read.csv(file.choose())
```
```{r}
head(xal3)
```
```{r}
str(xal3)
```
```{r}
summary(xal3)
```

### corrección de la columna 'Club'
```{r}
unique(xal3$Club)
```
```{r}
xal3_edit <- xal3 %>%
#XAL1
  mutate(Club=str_replace(Club, "XAL01", "XAL1")) %>%
  mutate(Club=str_replace(Club, "XAL 1", "XAL1")) %>%
  mutate(Club=str_replace(Club, "xal1", "XAL1")) %>%
#XAL2
  mutate(Club=str_replace(Club, "XAL 2", "XAL2")) %>%
  mutate(Club=str_replace(Club, "xal2", "XAL2")) 

```

### corrección de la columna 'Escuela'
```{r}
xal_edit <- xal3 %>%
  mutate(Escolaridad=str_replace(Escolaridad, "prepa", "Preparatoria"))%>%
  mutate(Escolaridad=str_replace(Escolaridad, "Prepa", "Preparatoria"))%>%
  mutate(Escolaridad=str_replace(Escolaridad, "UNI", "Universidad"))%>%
  mutate(Escolaridad=str_replace(Escolaridad, "univ", "Universidad"))%>%
  mutate(Escolaridad=str_replace(Escolaridad, "universidad", "Universidad"))
```

### corrección de la columna 'Sexo'
```{r}
xal3_edit <- xal3 %>%
  mutate(Sexo = str_replace(Sexo,"hombre", "M")) %>%
  mutate(Sexo = str_replace(Sexo,"h", "M")) %>%
  mutate(Sexo = str_replace(Sexo,"H", "M")) %>%
  mutate(Sexo = str_replace(Sexo,"mujer", "F")) %>%
  mutate(Sexo = str_replace(Sexo, "m", "F"))
```

### corrección de la columna 'Residencia'
```{r}
voc_local <- c("Local", "local", "LOCAL", "Xalapa", "xal")
voc_foraneo <- c("Foráneo", "for", "FORANEO")

xal3_edit <- xal3 %>%
  mutate(Residencia = ifelse(Residencia %in% voc_local, "Local", Residencia)) %>%
  mutate(Residencia = ifelse(Residencia %in% voc_foraneo, "Foraneo", Residencia))
```

### corrección de la columna 'Experiencia Previa'
```{r}
xal3_edit <-xal3 %>%
  mutate(ExperienciaPrevia =str_replace(ExperienciaPrevia,"Si", "SI"))%>%
  mutate(ExperienciaPrevia =str_replace(ExperienciaPrevia,"Sí", "SI"))%>%
  mutate(ExperienciaPrevia =str_replace(ExperienciaPrevia,"si", "SI"))%>%
  mutate(ExperienciaPrevia =str_replace(ExperienciaPrevia,"sí", "SI"))%>%
  mutate(ExperienciaPrevia =str_replace(ExperienciaPrevia,"no", "NO"))%>%
  mutate(ExperienciaPrevia =str_replace(ExperienciaPrevia,"No", "NO"))%>%
  mutate(ExperienciaPrevia =str_replace(ExperienciaPrevia,"SÍ", "SI"))
```


## revisar correcciones
```{r}
head(xal3_edit)
```



